#!bin/bash
tail -n +2 | cut -f -1 | sort -k 1 | uniq -c | sort -rnk 1 | head -n 11 | rev | cut -d  ' ' -f -1 | rev
tail -n +2 | sort | cut -f1 | uniq -c | sort -g -r | head 11 | tr -s " " | cut -d " " -f3
